import { randomUUID } from "node:crypto";
import type {
  PersonStats,
  VideoAnalysis,
  VideoJob,
  Workbench,
} from "./workbench-types";

export const emptyWorkbench = (): Workbench => ({
  version: 1,
  players: [],
  videos: [],
});
export function nextPlayerName(db: Workbench) {
  let number = 1;
  const names = new Set(db.players.map((p) => p.name));
  while (names.has(`球员 ${number}`)) number++;
  return `球员 ${number}`;
}
export function appearanceDistance(a: number[], b: number[]) {
  if (
    !a.length ||
    a.length !== b.length ||
    !a.every(Number.isFinite) ||
    !b.every(Number.isFinite)
  )
    return Infinity;
  return Math.sqrt(a.reduce((s, v, i) => s + (v - b[i]) ** 2, 0));
}

// Import exactly once per content hash. A poll, refresh, or re-upload cannot
// increment stored counters: totals are always derived from unique videos.
export function importAnalysis(
  db: Workbench,
  job: VideoJob,
  result: VideoAnalysis
) {
  if (job.result) return;
  if (
    result.videoKey !== job.id ||
    !Array.isArray(result.players) ||
    !Array.isArray(result.events)
  )
    throw new Error("分析结果与视频不匹配");
  const used = new Set<string>();
  for (const local of result.players) {
    const candidates = db.players
      .filter((p) => !p.archived && !used.has(p.id))
      .map((p) => ({
        p,
        distance: Math.max(
          Math.min(
            ...p.descriptors.map((d) =>
              appearanceDistance(d, local.anchor ?? local.descriptor)
            )
          ),
          (() => {
            const distances = (
              local.prototypes?.length ? local.prototypes : [local.descriptor]
            )
              .map((v) =>
                Math.min(...p.descriptors.map((d) => appearanceDistance(d, v)))
              )
              .sort((a, b) => a - b)
              .slice(0, 3);
            return distances[Math.floor(distances.length / 2)];
          })()
        ),
      }))
      .sort((a, b) => a.distance - b.distance);
    // Conservative clothing match. Different clothing / ambiguous colours
    // create a new identity which can be linked once by the user.
    const best = candidates[0];
    const match =
      best &&
      best.distance <
        (result.descriptorKind === "osnet-ain-msmt17-v1" ? 0.65 : 0.38) &&
      (!candidates[1] || candidates[1].distance - best.distance > 0.12);
    let person = match ? best.p : undefined;
    if (!person) {
      person = {
        id: randomUUID(),
        name: nextPlayerName(db),
        photo: local.photo,
        descriptors: [
          local.anchor ?? local.descriptor,
          ...(local.prototypes ?? [local.descriptor]),
        ].slice(0, 16),
        createdAt: new Date().toISOString(),
      };
      db.players.push(person);
    } else {
      job.autoMatched.push(local.id);
      person.descriptors = [
        ...person.descriptors.slice(-8),
        local.anchor ?? local.descriptor,
        ...(local.prototypes ?? [local.descriptor]).slice(0, 7),
      ];
    }
    used.add(person.id);
    job.associations[local.id] = person.id;
  }
  job.result = result;
  job.status = "complete";
  delete job.error;
}

export function replaceAnalysis(
  db: Workbench,
  job: VideoJob,
  result: VideoAnalysis
) {
  if (result.videoKey !== job.id) throw new Error("分析结果与视频不匹配");
  const old = new Set(Object.values(job.associations));
  const elsewhere = new Set(
    db.videos
      .filter((v) => v.id !== job.id)
      .flatMap((v) => Object.values(v.associations))
  );
  // Remove obsolete autogenerated fragments, but preserve named/edited people
  // and identities referenced by other videos. Prior records are archived.
  db.players = db.players.filter(
    (p) =>
      !old.has(p.id) ||
      elsewhere.has(p.id) ||
      p.edited ||
      p.roster ||
      !/^球员 \d+$/.test(p.name)
  );
  delete job.result;
  job.associations = {};
  job.autoMatched = [];
  importAnalysis(db, job, result);
}

export function personStatistics(
  db: Workbench,
  videoId?: string
): PersonStats[] {
  const jobs = db.videos.filter(
    (v) => v.result && (!videoId || v.id === videoId)
  );
  return db.players
    .map((p) => {
      const videos = jobs.filter((v) =>
        Object.values(v.associations).includes(p.id)
      );
      const events = videos.flatMap((v) =>
        v.result!.events.filter(
          (e) =>
            e.status === "estimated" &&
            e.playerId &&
            v.associations[e.playerId] === p.id
        )
      );
      const knownPoints = events.reduce((n, e) => n + (e.points ?? 0), 0);
      const unknownValue = events.filter((e) => e.points === null).length;
      return {
        id: p.id,
        name: p.name,
        photo: p.photo,
        jerseyNumber: p.jerseyNumber,
        roster: p.roster,
        archived: p.archived,
        videos: videos.length,
        made: events.length,
        knownPoints,
        unknownValue,
        pointsMin: knownPoints,
        pointsMax: knownPoints,
      };
    })
    .filter((p) => !videoId || p.videos > 0)
    .sort(
      (a, b) =>
        b.knownPoints - a.knownPoints ||
        b.made - a.made ||
        a.name.localeCompare(b.name, "zh-CN", { numeric: true })
    );
}

export function mergePeople(db: Workbench, source: string, target: string) {
  if (source === target) throw new Error("请选择另一位球员");
  const from = db.players.find((p) => p.id === source),
    to = db.players.find((p) => p.id === target);
  if (!from || !to) throw new Error("球员不存在");
  for (const v of db.videos)
    for (const local of Object.keys(v.associations))
      if (v.associations[local] === source) v.associations[local] = target;
  to.descriptors = [...to.descriptors, ...from.descriptors].slice(-12);
  to.edited = true;
  to.roster = to.roster || from.roster;
  to.jerseyNumber = to.jerseyNumber ?? from.jerseyNumber;
  to.sourceRefs = Array.from(
    new Set([...(to.sourceRefs ?? []), ...(from.sourceRefs ?? [])])
  );
  to.referencePhotos = [
    ...(to.referencePhotos ?? []),
    ...(from.referencePhotos ?? []),
  ].filter((p, i, a) => a.findIndex((q) => q.id === p.id) === i);
  if (
    !to.referencePhotos?.length &&
    to.photo === "/assets/player-placeholder.svg"
  )
    to.photo = from.photo;
  else if (
    to.referencePhotos?.length &&
    to.photo === "/assets/player-placeholder.svg"
  )
    to.photo = to.referencePhotos[0].url;
  db.players = db.players.filter((p) => p.id !== source);
}

export function relinkPerson(
  db: Workbench,
  videoId: string,
  localId: string,
  target: string
) {
  const job = db.videos.find((v) => v.id === videoId);
  const local = job?.result?.players.find((p) => p.id === localId);
  if (!job || !local || !db.players.some((p) => p.id === target && !p.archived))
    throw new Error("球员或视频不存在");
  job.associations[localId] = target;
  job.autoMatched = job.autoMatched.filter((id) => id !== localId);
  const person = db.players.find((p) => p.id === target)!;
  person.edited = true;
  person.descriptors = [...person.descriptors, local.descriptor].slice(-12);
}
